# SQL vs Pandas Project

## Aim: To show some SQL style operations in Pandas 

### Introduction

> This notebook demonstrates some SQL style manipulations of a dataset in Pandas.
> 
> The two datasets used are from Kaggle:
> 1. Heart Disease
> [Heart disease Kaggle data](https://www.kaggle.com/datasets/oktayrdeki/heart-disease/data)
> 2. Heart Attack Risk Prediction
> [Heart disease Kaggle data](https://www.kaggle.com/datasets/iamsouravbanerjee/heart-attack-prediction-dataset)
> 
> - The first Heart Disease Data demonstrates the initial data manipulations 
> - Whilst the Heart Attack Risk Prediction is used to illustrate joins.
> 
> The notebook shows some initial steps before going into the SQL style data manipulations:
> - importing the pandas library.
> - reading in the csv file.
> - some initial memory optimization.

In [2]:
# import the pandas library
import pandas as pd

In [3]:
heart_dis = pd.read_csv("../notebooks/project-dataset/heart_disease.csv")  # read in the file
heart_dis.nunique() # gives all the unique values for all the columns within the dataset and that can help to prioritise the columns to categorise.

Age                       63
Gender                     2
Blood Pressure            61
Cholesterol Level        151
Exercise Habits            3
Smoking                    2
Family Heart Disease       2
Diabetes                   2
BMI                     9978
High Blood Pressure        2
Low HDL Cholesterol        2
High LDL Cholesterol       2
Alcohol Consumption        3
Stress Level               3
Sleep Hours             9975
Sugar Consumption          3
Triglyceride Level       301
Fasting Blood Sugar       81
CRP Level               9974
Homocysteine Level      9980
Heart Disease Status       2
dtype: int64

The **info()** method summarises each column in the dataframe by giving the count of the non-null values and each column's datatype

In [4]:
heart_dis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   object
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   object
 5   Smoking               9975 non-null   object
 6   Family Heart Disease  9979 non-null   object
 7   Diabetes              9970 non-null   object
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object
 10  Low HDL Cholesterol   9975 non-null   object
 11  High LDL Cholesterol  9974 non-null   object
 12  Alcohol Consumption   7414 non-null   object
 13  Stress Level          9978 non-null   object
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   object
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), object(12)
memory usage: 1.6+ MB

#### Memory optimisation for first dataset
- Reduce the memory usage by storing some columns as a category type 
- The category type is suitable for columns with a limited number of unique values

In [5]:
# reduce the memory usage by storing some columns as a category type 
heart_dis["Gender"] = heart_dis["Gender"].astype("category") # gender
heart_dis["Exercise Habits"] = heart_dis["Exercise Habits"].astype("category") # "Exercise Habits
heart_dis["Smoking"] = heart_dis["Smoking"].astype("category") # Smoking
heart_dis["Family Heart Disease"] = heart_dis["Family Heart Disease"].astype("category") # Family Heart Disease
heart_dis["Diabetes"] = heart_dis["Diabetes"].astype("category")# Diabetes
heart_dis["High Blood Pressure"] = heart_dis["High Blood Pressure"].astype("category") # High Blood Pressure
heart_dis["Low HDL Cholesterol"] = heart_dis["Low HDL Cholesterol"].astype("category") # Low HDL Cholesterol 
heart_dis["High LDL Cholesterol"] = heart_dis["High LDL Cholesterol"].astype("category") # High LDL Cholesterol
heart_dis["Alcohol Consumption"] = heart_dis["Alcohol Consumption"].astype("category") # Alcohol Consumption
heart_dis["Stress Level"] = heart_dis["Stress Level"].astype("category") # Stress Level
heart_dis["Sugar Consumption"] = heart_dis["Sugar Consumption"].astype("category") # Sugar Consumption
heart_dis["Heart Disease Status"] = heart_dis["Heart Disease Status"].astype("category") # Heart Disease Status
heart_dis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   category
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   category
 5   Smoking               9975 non-null   category
 6   Family Heart Disease  9979 non-null   category
 7   Diabetes              9970 non-null   category
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   category
 10  Low HDL Cholesterol   9975 non-null   category
 11  High LDL Cholesterol  9974 non-null   category
 12  Alcohol Consumption   7414 non-null   category
 13  Stress Level          9978 non-null   category
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   category
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  category
dtypes: category(12), float64(9)
memory usage: 821.9 KB

### Comparison 1

#### Show a subset of data
The next 2 cells display 
- the top 10 rows from the dataset
- the last 10 rows from the dataset

In [6]:
# show the top 10 rows in the dataframe
heart_dis.head(10)

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
5,25.0,Male,152.0,257.0,Low,Yes,No,No,28.144681,No,...,No,Low,Medium,5.504876,Low,126.0,91.0,4.297575,10.815983,No
6,78.0,Female,121.0,175.0,High,Yes,Yes,Yes,18.042332,No,...,No,Medium,Medium,9.240911,Medium,107.0,85.0,11.582983,19.659461,No
7,38.0,Female,161.0,187.0,Low,Yes,Yes,Yes,34.736683,No,...,No,Low,Medium,7.841008,High,228.0,111.0,4.929381,17.146599,No
8,56.0,Female,135.0,291.0,Low,No,Yes,Yes,34.493112,Yes,...,Yes,High,Low,6.941403,High,317.0,103.0,5.119015,6.051129,No
9,75.0,Male,144.0,252.0,Low,Yes,Yes,No,30.142149,No,...,Yes,Low,Medium,4.002662,High,199.0,96.0,10.005698,7.604357,No

In [7]:
# show the last 10 rows in the dataframe
heart_dis.tail(10)

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
9990,55.0,Female,131.0,160.0,High,Yes,No,Yes,32.363462,No,...,No,Low,Medium,5.018783,Medium,267.0,129.0,0.603213,11.298252,Yes
9991,41.0,Female,160.0,241.0,Medium,No,Yes,Yes,39.346342,Yes,...,Yes,NaN,High,4.343666,Low,178.0,106.0,4.718864,14.219791,Yes
9992,68.0,Female,169.0,291.0,Medium,Yes,No,No,22.839718,No,...,No,Medium,Low,6.057509,High,299.0,142.0,3.321020,11.910244,Yes
9993,27.0,Female,153.0,188.0,Medium,No,No,Yes,28.173059,Yes,...,No,NaN,Medium,4.834842,High,300.0,118.0,6.216700,13.114808,Yes
9994,73.0,Female,144.0,191.0,Medium,Yes,Yes,Yes,39.459620,No,...,No,Medium,Low,7.549114,Medium,200.0,88.0,1.154904,8.021732,Yes
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes
9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,...,Yes,NaN,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,...,Yes,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes

#### Select a single column from the dataframe

In [8]:
# Select the Exercise Habits column from the dataframe
heart_dis["Exercise Habits"]

0         High
1         High
2          Low
3         High
4          Low
         ...
9995    Medium
9996    Medium
9997      High
9998       Low
9999    Medium
Name: Exercise Habits, Length: 10000, dtype: category
Categories (3, object): ['High', 'Low', 'Medium']

#### Select multiple columns from the dataframe

In [9]:
# Select the Age, Cholesterol Level and Heart Disease Status columns from the dataframe
heart_dis[["Age", "Cholesterol Level", "Heart Disease Status"]]

       Age  Cholesterol Level Heart Disease Status
0     56.0              155.0                   No
1     69.0              286.0                   No
2     46.0              216.0                   No
3     32.0              293.0                   No
4     60.0              242.0                   No
...    ...                ...                  ...
9995  25.0              243.0                  Yes
9996  38.0              154.0                  Yes
9997  73.0              201.0                  Yes
9998  23.0              299.0                  Yes
9999  38.0              193.0                  Yes

[10000 rows x 3 columns]

### Comparison 2

#### Modifying data; Adding a new column to the dataset 
- Create a new column that adds 2 to all the sleep hours for each record
- This will be added at the end of the dataframe.
- *[Updated Sleep Hours]* which is the original sleep hours + 2

In [10]:
# Create a new column that adds 2 to all the sleep hours for each record
# This will be added at the end of the dataframe.
heart_dis["Updated Sleep Hours"] = heart_dis["Sleep Hours"]+ 2
heart_dis.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Updated Sleep Hours
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No,9.633228
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No,10.744034
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No,6.440440
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No,7.249405
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No,9.030971

#### Selecting multiple columns from the dataframe including the newly created column *[Updated Sleep Hours]*

In [11]:
# Select the "Blood Pressure", "High Blood Pressure", "Stress Level", "Sleep Hours", "Updated Sleep Hours columns from the dataframe
heart_dis[["Blood Pressure", "High Blood Pressure", "Stress Level", "Sleep Hours", "Updated Sleep Hours"]]

,Blood Pressure,High Blood Pressure,Stress Level,Sleep Hours,Updated Sleep Hours
0,153.0,Yes,Medium,7.633228,9.633228
1,146.0,No,High,8.744034,10.744034
2,126.0,No,Low,4.440440,6.440440
3,122.0,Yes,High,5.249405,7.249405
4,166.0,Yes,High,7.030971,9.030971
...,...,...,...,...,...
9995,136.0,Yes,High,6.834954,8.834954
9996,172.0,Yes,High,8.247784,10.247784
9997,152.0,No,Low,4.436762,6.436762
9998,142.0,Yes,High,8.526329,10.526329
9999,128.0,No,Medium,5.659394,7.659394

#### Add a new column at a specified location within the dataframe

- The new column is **Exercise Type** and it will be added after **Exercise Habits**
- The insert method is called to put the new column in a specified location.

In [12]:
# the insert function allows the new column Exercise Type to be added at the specified position. It will shift all the pre-existing columns to the right

heart_dis.insert(loc=5, column="Exercise Type", value="Walking")
heart_dis.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Exercise Type,Smoking,Family Heart Disease,Diabetes,BMI,...,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Updated Sleep Hours
0,56.0,Male,153.0,155.0,High,Walking,Yes,Yes,No,24.991591,...,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No,9.633228
1,69.0,Female,146.0,286.0,High,Walking,No,Yes,Yes,25.221799,...,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No,10.744034
2,46.0,Male,126.0,216.0,Low,Walking,No,No,No,29.855447,...,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No,6.440440
3,32.0,Female,122.0,293.0,High,Walking,Yes,Yes,No,24.130477,...,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No,7.249405
4,60.0,Male,166.0,242.0,Low,Walking,Yes,Yes,Yes,20.486289,...,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No,9.030971

#### Selecting multiple columns from the dataframe including the newly created column *[Exercise Type]*

In [13]:
# Select the "Blood Pressure", "High Blood Pressure", "Exercise Habits", "Exercise Type" columns from the dataframe
heart_dis[["Blood Pressure", "High Blood Pressure", "Exercise Habits", "Exercise Type"]]

      Blood Pressure High Blood Pressure Exercise Habits Exercise Type
0              153.0                 Yes            High       Walking
1              146.0                  No            High       Walking
2              126.0                  No             Low       Walking
3              122.0                 Yes            High       Walking
4              166.0                 Yes             Low       Walking
...              ...                 ...             ...           ...
9995           136.0                 Yes          Medium       Walking
9996           172.0                 Yes          Medium       Walking
9997           152.0                  No            High       Walking
9998           142.0                 Yes             Low       Walking
9999           128.0                  No          Medium       Walking

[10000 rows x 4 columns]

### Comparison 3

#### Frequency Distribution of value in a dataset

The value_counts mentod is used to achieve this.
- In the example below, there are 3 values for Exercise Habits and the frequency for each type is provided.

In [14]:
# Count the number of each occurrence of the Exercise Habits values.
heart_dis["Exercise Habits"].value_counts()

Exercise Habits
High      3372
Medium    3332
Low       3271
Name: count, dtype: int64

nunique will tell you the number of unique values in each column

In [15]:
# Identify the number of unique/distinct Exercise Habits values.
heart_dis["Exercise Habits"].nunique()

3

### Comparison 4

#### Filtering with 1 condition

In [16]:
# show all the people with a family history of heart disease.
has_family_history = heart_dis["Family Heart Disease"] == "Yes"
heart_dis[has_family_history]

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Exercise Type,Smoking,Family Heart Disease,Diabetes,BMI,...,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Updated Sleep Hours
0,56.0,Male,153.0,155.0,High,Walking,Yes,Yes,No,24.991591,...,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No,9.633228
1,69.0,Female,146.0,286.0,High,Walking,No,Yes,Yes,25.221799,...,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No,10.744034
3,32.0,Female,122.0,293.0,High,Walking,Yes,Yes,No,24.130477,...,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No,7.249405
4,60.0,Male,166.0,242.0,Low,Walking,Yes,Yes,Yes,20.486289,...,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No,9.030971
6,78.0,Female,121.0,175.0,High,Walking,Yes,Yes,Yes,18.042332,...,Medium,Medium,9.240911,Medium,107.0,85.0,11.582983,19.659461,No,11.240911
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,34.0,Male,126.0,166.0,Medium,Walking,No,Yes,Yes,28.693536,...,Medium,High,7.233239,Low,378.0,116.0,11.152744,13.533806,Yes,9.233239
9989,67.0,Male,176.0,154.0,Low,Walking,Yes,Yes,Yes,23.359268,...,Low,High,9.269228,Medium,203.0,150.0,7.869564,6.530321,Yes,11.269228
9991,41.0,Female,160.0,241.0,Medium,Walking,No,Yes,Yes,39.346342,...,NaN,High,4.343666,Low,178.0,106.0,4.718864,14.219791,Yes,6.343666
9994,73.0,Female,144.0,191.0,Medium,Walking,Yes,Yes,Yes,39.459620,...,Medium,Low,7.549114,Medium,200.0,88.0,1.154904,8.021732,Yes,9.549114
9999,38.0,Female,128.0,193.0,Medium,Walking,Yes,Yes,Yes,25.111295,...,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes,7.659394

### Filtering with multiple conditions (AND Logic)

In [17]:
# show all people with diabetes and have a high sugar consumption
has_diabetes = heart_dis["Diabetes"] == "Yes"
heart_dis[has_diabetes]

has_high_sugar_consumption = heart_dis["Sugar Consumption"] == "High"
heart_dis[has_high_sugar_consumption]

heart_dis[has_diabetes & has_high_sugar_consumption]

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Exercise Type,Smoking,Family Heart Disease,Diabetes,BMI,...,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Updated Sleep Hours
4,60.0,Male,166.0,242.0,Low,Walking,Yes,Yes,Yes,20.486289,...,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No,9.030971
7,38.0,Female,161.0,187.0,Low,Walking,Yes,Yes,Yes,34.736683,...,Low,Medium,7.841008,High,228.0,111.0,4.929381,17.146599,No,9.841008
8,56.0,Female,135.0,291.0,Low,Walking,No,Yes,Yes,34.493112,...,High,Low,6.941403,High,317.0,103.0,5.119015,6.051129,No,8.941403
17,57.0,Female,133.0,245.0,Low,Walking,No,Yes,Yes,26.519301,...,Medium,High,4.731453,High,384.0,132.0,0.028436,14.306619,No,6.731453
26,55.0,Male,159.0,259.0,Low,Walking,Yes,No,Yes,19.265130,...,Low,High,4.167873,High,180.0,146.0,0.907313,10.103030,No,6.167873
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9972,26.0,Female,130.0,168.0,High,Walking,Yes,Yes,Yes,30.768461,...,NaN,High,6.302458,High,262.0,114.0,0.543114,7.862505,Yes,8.302458
9976,55.0,Male,168.0,271.0,Medium,Walking,Yes,Yes,Yes,34.113013,...,Medium,High,4.925255,High,176.0,149.0,12.006368,7.889586,Yes,6.925255
9984,79.0,Male,168.0,248.0,Medium,Walking,No,Yes,Yes,30.971385,...,High,Low,4.087551,High,374.0,80.0,14.341145,10.757579,Yes,6.087551
9993,27.0,Female,153.0,188.0,Medium,Walking,No,No,Yes,28.173059,...,NaN,Medium,4.834842,High,300.0,118.0,6.216700,13.114808,Yes,6.834842
9999,38.0,Female,128.0,193.0,Medium,Walking,Yes,Yes,Yes,25.111295,...,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes,7.659394

### Filtering data with either/or conditions (OR Logic)

In [18]:
# show all people that either smoke or have a high alcohol consumption

smokes  = heart_dis["Smoking"] == "Yes"

high_alcohol = heart_dis["Alcohol Consumption"] == "High"

heart_dis[smokes | high_alcohol]

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Exercise Type,Smoking,Family Heart Disease,Diabetes,BMI,...,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Updated Sleep Hours
0,56.0,Male,153.0,155.0,High,Walking,Yes,Yes,No,24.991591,...,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No,9.633228
3,32.0,Female,122.0,293.0,High,Walking,Yes,Yes,No,24.130477,...,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No,7.249405
4,60.0,Male,166.0,242.0,Low,Walking,Yes,Yes,Yes,20.486289,...,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No,9.030971
5,25.0,Male,152.0,257.0,Low,Walking,Yes,No,No,28.144681,...,Low,Medium,5.504876,Low,126.0,91.0,4.297575,10.815983,No,7.504876
6,78.0,Female,121.0,175.0,High,Walking,Yes,Yes,Yes,18.042332,...,Medium,Medium,9.240911,Medium,107.0,85.0,11.582983,19.659461,No,11.240911
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,73.0,Female,144.0,191.0,Medium,Walking,Yes,Yes,Yes,39.459620,...,Medium,Low,7.549114,Medium,200.0,88.0,1.154904,8.021732,Yes,9.549114
9995,25.0,Female,136.0,243.0,Medium,Walking,Yes,No,No,18.788791,...,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes,8.834954
9997,73.0,Male,152.0,201.0,High,Walking,Yes,No,Yes,26.899911,...,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes,6.436762
9998,23.0,Male,142.0,299.0,Low,Walking,Yes,No,Yes,34.964026,...,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes,10.526329
9999,38.0,Female,128.0,193.0,Medium,Walking,Yes,Yes,Yes,25.111295,...,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes,7.659394

### Filtering for multiple values

- Using the isin() method

In [19]:
# show all people with a blood pressure of specific values: 150, 160, 170
target_bp = heart_dis["Blood Pressure"].isin([150.0, 160.0, 170.0])
heart_dis[target_bp]

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Exercise Type,Smoking,Family Heart Disease,Diabetes,BMI,...,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Updated Sleep Hours
14,41.0,Female,150.0,187.0,High,Walking,No,Yes,No,37.387840,...,Medium,Low,9.624732,Low,343.0,124.0,10.051791,9.897205,No,11.624732
23,41.0,Female,170.0,300.0,Low,Walking,No,No,No,20.661064,...,NaN,Low,6.438116,Low,317.0,116.0,1.739325,14.225836,No,8.438116
57,68.0,Male,160.0,225.0,Medium,Walking,No,No,No,37.201106,...,NaN,High,5.000253,High,110.0,103.0,7.345541,11.578776,No,7.000253
97,80.0,Male,160.0,261.0,High,Walking,No,Yes,Yes,32.520722,...,High,Low,9.867194,Low,228.0,128.0,5.408203,11.780861,No,11.867194
102,27.0,Male,160.0,265.0,High,Walking,Yes,Yes,No,36.495297,...,Low,Medium,6.715802,Low,310.0,94.0,11.719268,9.987728,No,8.715802
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9941,25.0,Male,160.0,162.0,Low,Walking,No,No,Yes,37.582862,...,Low,Medium,7.231939,High,111.0,84.0,8.619376,9.822503,Yes,9.231939
9944,77.0,Male,160.0,280.0,Low,Walking,Yes,Yes,Yes,27.048995,...,Low,Medium,7.186142,Medium,246.0,148.0,9.844135,11.314064,Yes,9.186142
9967,56.0,Male,170.0,242.0,Medium,Walking,No,No,No,30.975713,...,Low,Low,7.219204,Low,326.0,128.0,3.673993,16.703529,Yes,9.219204
9981,61.0,Male,150.0,219.0,Medium,Walking,Yes,Yes,No,34.129304,...,Low,Medium,9.870118,Low,227.0,92.0,4.886448,9.630636,Yes,11.870118
9991,41.0,Female,160.0,241.0,Medium,Walking,No,Yes,Yes,39.346342,...,NaN,High,4.343666,Low,178.0,106.0,4.718864,14.219791,Yes,6.343666

### Second Dataset
This section introduces the second dataset Heart Attack Risk Prediction

In [20]:
heart_att = pd.read_csv("../notebooks/project-dataset/heart_attack_prediction_dataset.csv")  # read in the file
heart_att.nunique() # gives all the unique values for all the columns within the dataset and that can help to prioritise the columns to categorise.

Patient ID                         8763
Age                                  73
Sex                                   2
Cholesterol                         281
Blood Pressure                     3915
Heart Rate                           71
Diabetes                              2
Family History                        2
Smoking                               2
Obesity                               2
Alcohol Consumption                   2
Exercise Hours Per Week            8763
Diet                                  3
Previous Heart Problems               2
Medication Use                        2
Stress Level                         10
Sedentary Hours Per Day            8763
Income                             8615
BMI                                8763
Triglycerides                       771
Physical Activity Days Per Week       8
Sleep Hours Per Day                   7
Country                              20
Continent                             6
Hemisphere                            2
Heart Attack Risk                     2
dtype: int64

The **info()** method summarises each column in the dataframe by giving the count of the non-null values and each column's datatype

In [21]:
heart_att.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Patient ID                       8763 non-null   object
 1   Age                              8763 non-null   int64
 2   Sex                              8763 non-null   object
 3   Cholesterol                      8763 non-null   int64
 4   Blood Pressure                   8763 non-null   object
 5   Heart Rate                       8763 non-null   int64
 6   Diabetes                         8763 non-null   int64
 7   Family History                   8763 non-null   int64
 8   Smoking                          8763 non-null   int64
 9   Obesity                          8763 non-null   int64
 10  Alcohol Consumption              8763 non-null   int64
 11  Exercise Hours Per Week          8763 non-null   float64
 12  Diet                             8763 non-null   object
 13  Previous Heart Problems          8763 non-null   int64
 14  Medication Use                   8763 non-null   int64
 15  Stress Level                     8763 non-null   int64
 16  Sedentary Hours Per Day          8763 non-null   float64
 17  Income                           8763 non-null   int64
 18  BMI                              8763 non-null   float64
 19  Triglycerides                    8763 non-null   int64
 20  Physical Activity Days Per Week  8763 non-null   int64
 21  Sleep Hours Per Day              8763 non-null   int64
 22  Country                          8763 non-null   object
 23  Continent                        8763 non-null   object
 24  Hemisphere                       8763 non-null   object
 25  Heart Attack Risk                8763 non-null   int64
dtypes: float64(3), int64(16), object(7)
memory usage: 1.7+ MB

#### Memory optimisation for second dataset
- Reduce the memory usage by storing some columns as a category type 
- The category type is suitable for columns with a limited number of unique values

In [22]:
# reduce the memory usage by storing some columns as a category type 
heart_att["Sex"] = heart_att["Sex"].astype("category") # Sex
heart_att["Diabetes"] = heart_att["Diabetes"].astype("category")# Diabetes
heart_att["Family History"] = heart_att["Family History"].astype("category")# Family History
heart_att["Smoking"] = heart_att["Smoking"].astype("category") # Smoking
heart_att["Obesity"] = heart_att["Obesity"].astype("category") # Obesity
heart_att["Alcohol Consumption"] = heart_att["Alcohol Consumption"].astype("category") # Alcohol Consumption
heart_att["Diet"] = heart_att["Diet"].astype("category") # Diet
heart_att["Previous Heart Problems"] = heart_att["Previous Heart Problems"].astype("category") # Previous Heart Problems
heart_att["Medication Use"] = heart_att["Medication Use"].astype("category") # Medication Use
#heart_att["Stress Level"] = heart_att["Stress Level"].astype("category") # Stress Level
heart_att["Physical Activity Days Per Week"] = heart_att["Physical Activity Days Per Week"].astype("category") # Physical Activity Days Per Week
heart_att["Sleep Hours Per Day"] = heart_att["Sleep Hours Per Day"].astype("category") # Sleep Hours Per Day
#heart_att["Country"] = heart_att["Country"].astype("category") # Country
heart_att["Continent"] = heart_att["Continent"].astype("category") # Continent
heart_att["Hemisphere"] = heart_att["Hemisphere"].astype("category") # Hemisphere
heart_att["Heart Attack Risk"] = heart_att["Heart Attack Risk"].astype("category") #Heart Attack Risk
heart_att.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Patient ID                       8763 non-null   object
 1   Age                              8763 non-null   int64
 2   Sex                              8763 non-null   category
 3   Cholesterol                      8763 non-null   int64
 4   Blood Pressure                   8763 non-null   object
 5   Heart Rate                       8763 non-null   int64
 6   Diabetes                         8763 non-null   category
 7   Family History                   8763 non-null   category
 8   Smoking                          8763 non-null   category
 9   Obesity                          8763 non-null   category
 10  Alcohol Consumption              8763 non-null   category
 11  Exercise Hours Per Week          8763 non-null   float64
 12  Diet                             8763 non-null   category
 13  Previous Heart Problems          8763 non-null   category
 14  Medication Use                   8763 non-null   category
 15  Stress Level                     8763 non-null   int64
 16  Sedentary Hours Per Day          8763 non-null   float64
 17  Income                           8763 non-null   int64
 18  BMI                              8763 non-null   float64
 19  Triglycerides                    8763 non-null   int64
 20  Physical Activity Days Per Week  8763 non-null   category
 21  Sleep Hours Per Day              8763 non-null   category
 22  Country                          8763 non-null   object
 23  Continent                        8763 non-null   category
 24  Hemisphere                       8763 non-null   category
 25  Heart Attack Risk                8763 non-null   category
dtypes: category(14), float64(3), int64(6), object(3)
memory usage: 943.7+ KB

In [23]:
# show the top 5 rows of the heart attack dataset as a preview to the dataset
heart_att.head()

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,...,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,CZE1114,21,Male,389,165/93,98,1,1,1,1,...,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,BNI9906,21,Female,324,174/99,72,1,0,0,0,...,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,JLN3497,84,Male,383,163/100,73,1,1,1,0,...,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,GFO8847,66,Male,318,91/88,93,1,1,1,1,...,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0

### Comparison 5

#### Sorting Data  
- Sort data by one column (ascending, descending order)
- Sort data by multiple columns (ascending, descending order)

***Sort data by one column (ascending order)***

In [43]:
# sort the data by the Sedentary Hours Per Day (ascending order)
heart_att.sort_values("Sedentary Hours Per Day", ascending=True).head(10)

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
3314,RWL0019,36,Male,187,108/108,75,1,1,1,1,...,0.001263,268146,26.639356,386,5,4,Japan,Asia,Northern Hemisphere,0
865,FPU3089,20,Male,376,123/97,55,1,0,1,0,...,0.001529,293544,34.065753,210,5,9,Canada,North America,Northern Hemisphere,1
2356,QET6776,39,Male,212,95/109,43,1,0,1,1,...,0.003625,159807,21.245085,743,6,7,Japan,Asia,Northern Hemisphere,0
970,WVH1070,28,Female,156,144/108,68,1,1,0,0,...,0.008307,154637,37.493822,261,7,5,United States,North America,Northern Hemisphere,0
1915,EQU4458,34,Male,205,120/101,93,1,0,1,1,...,0.010631,211467,34.369766,570,2,5,Canada,North America,Northern Hemisphere,0
5550,MGF4699,41,Male,283,134/68,77,0,0,1,1,...,0.015174,52993,19.819781,129,3,9,Australia,Australia,Southern Hemisphere,0
8400,PVZ0721,38,Female,300,159/99,87,1,0,0,1,...,0.015503,85914,34.304193,583,0,8,France,Europe,Northern Hemisphere,1
1102,BCA2764,78,Male,321,157/105,72,1,1,1,1,...,0.015910,254508,27.590278,454,4,5,United States,North America,Northern Hemisphere,0
5181,HCW3172,66,Male,137,130/106,80,1,1,1,1,...,0.020509,129823,34.611710,51,7,4,Nigeria,Africa,Northern Hemisphere,1
1097,GCQ0562,30,Male,274,107/95,90,1,0,1,0,...,0.022075,134796,37.492111,120,3,10,Spain,Europe,Southern Hemisphere,0

***Sort data by one column (descending order)***

In [25]:
# sort the data by BMI (descending order)
heart_att.sort_values("BMI", ascending=False).head(10)

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
136,AZR0892,82,Male,378,118/105,96,1,1,1,0,...,6.245146,230457,39.997211,286,2,4,Nigeria,Africa,Northern Hemisphere,1
206,IED0019,58,Female,351,176/110,89,1,0,1,0,...,5.953287,257788,39.993581,202,4,8,New Zealand,Australia,Southern Hemisphere,0
1728,DKP7955,39,Male,343,180/101,83,0,1,1,0,...,2.765502,231769,39.989915,129,6,9,Argentina,South America,Southern Hemisphere,0
6957,UBC9246,61,Male,308,94/103,41,0,0,1,1,...,11.915408,224974,39.986127,523,7,7,Brazil,South America,Southern Hemisphere,1
5443,JGG3063,68,Female,190,157/109,62,1,0,1,1,...,3.743081,177364,39.985120,476,1,6,Colombia,South America,Northern Hemisphere,1
3548,TEM1331,23,Male,275,115/63,110,0,0,1,0,...,10.691582,75657,39.984343,535,7,6,France,Europe,Northern Hemisphere,1
4260,LOW5440,28,Male,130,139/65,74,1,1,1,0,...,3.201966,195166,39.980327,289,2,9,Nigeria,Africa,Northern Hemisphere,1
2750,ZJO3101,59,Female,190,153/63,96,1,0,1,1,...,11.171361,206638,39.979234,427,5,8,South Africa,Africa,Southern Hemisphere,1
1428,NMZ4210,30,Male,230,109/65,44,1,1,1,0,...,8.400889,105125,39.978977,122,1,7,Colombia,South America,Northern Hemisphere,0
2958,EJC4381,57,Male,199,103/110,98,1,0,1,0,...,4.393919,140279,39.977267,581,2,9,France,Europe,Northern Hemisphere,1

***Sort data by multiple columns (both in ascending order)***

In [26]:
# sort the data by age (ascending order) and income (ascending order)
heart_att.sort_values(["Age", "Income"]).head(10)

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
753,UQA6590,18,Male,386,165/110,56,1,1,1,1,...,2.879953,24138,25.259222,347,5,7,France,Europe,Northern Hemisphere,1
7463,JRW1358,18,Female,382,104/85,70,1,0,0,1,...,5.304886,26833,32.548304,797,5,4,Argentina,South America,Southern Hemisphere,0
6816,QVG9493,18,Male,143,119/81,58,1,1,1,1,...,11.524238,27382,35.639114,326,3,6,Australia,Australia,Southern Hemisphere,0
7146,ROM7758,18,Male,167,116/78,107,1,1,1,1,...,7.170642,29689,35.683542,515,0,10,Argentina,South America,Southern Hemisphere,0
8111,GXY2968,18,Male,148,109/99,64,1,0,1,0,...,8.674298,32544,27.928065,173,5,9,South Korea,Asia,Northern Hemisphere,0
785,XWE7501,18,Female,120,162/102,99,0,1,0,1,...,7.400342,32612,34.490889,184,2,5,China,Asia,Northern Hemisphere,0
2423,MUH8083,18,Female,335,96/103,77,0,1,0,1,...,5.451757,33018,19.643974,322,6,7,France,Europe,Northern Hemisphere,0
4778,AHG7358,18,Female,207,178/63,108,1,0,0,0,...,4.083577,36330,30.534401,215,0,8,Vietnam,Asia,Northern Hemisphere,0
6368,GWZ2697,18,Male,172,168/71,83,0,0,1,1,...,1.651292,37653,38.503929,637,5,4,Argentina,South America,Southern Hemisphere,0
4836,YWX4696,18,Male,340,156/63,105,0,1,1,1,...,11.538666,38949,39.133721,775,4,4,Brazil,South America,Southern Hemisphere,1

***Sort data by multiple columns (the first in ascending order, the subsequent two in descending order)***

In [27]:
# sort the data by Continent (ascending order), Heart Rate (descending order) and Sleep Hours Per Day (descending order)
heart_att.sort_values(["Continent", "Heart Rate", "Sleep Hours Per Day"], ascending=[True, False, False])

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
2232,VAZ4776,43,Female,386,180/70,110,0,1,1,0,...,8.235336,32900,29.997139,515,3,10,Nigeria,Africa,Northern Hemisphere,1
3166,GLU8885,87,Male,250,100/92,110,0,0,1,0,...,4.617026,252802,31.247345,404,6,10,South Africa,Africa,Southern Hemisphere,1
4101,CXN0232,38,Female,150,100/73,110,1,0,0,1,...,7.510334,195248,25.695394,75,6,10,South Africa,Africa,Southern Hemisphere,0
5870,HGQ2341,72,Male,326,110/64,110,1,0,1,1,...,11.682387,46642,21.204043,348,3,10,Nigeria,Africa,Northern Hemisphere,0
8667,DAS1914,38,Male,305,135/91,110,1,0,1,1,...,5.632489,54783,33.195554,80,6,10,South Africa,Africa,Southern Hemisphere,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,KGL2227,74,Male,125,142/103,40,0,1,1,1,...,2.385524,268185,37.532102,523,7,5,Colombia,South America,Northern Hemisphere,0
2968,BLN8384,33,Male,329,93/104,40,1,1,1,1,...,5.293286,158808,27.846813,67,5,5,Brazil,South America,Southern Hemisphere,1
3439,XSM4149,69,Male,354,112/82,40,0,0,1,0,...,11.955433,289927,29.251141,491,6,4,Colombia,South America,Northern Hemisphere,0
5099,CDO9288,49,Female,380,144/62,40,1,0,1,1,...,5.448155,84566,29.089213,159,2,4,Colombia,South America,Northern Hemisphere,0
8291,PCA8678,41,Male,388,169/76,40,1,0,1,1,...,10.308719,201810,20.592500,50,4,4,Argentina,South America,Southern Hemisphere,1

### Data Manipulation
The second heart attack risk dataset has a patient id to uniquely identify each record but the first heart disease dataset doesn't. In order to illustrate the join examples, a subset of the first heart disease dataset will be modified to include a synthetic patient id.
Two additional datasets will be used and these are subsets of the heart attack risk dataset.
- female_data
- male_data
- Both dataset have the following fields: patient id, Age and Sex

##### Step 1
Extract a subset of heart disease data and add the patient ids from the female_data

##### 1.1 Clean the heart disease age column

In [28]:
heart_dis["Age"].sort_values() # sorting the age column shows that there are missing values

# remove the missing values before converting it to Integer to match the heart attack data
heart_dis_subset = heart_dis.dropna(subset=["Age"]) # drops the rows for the specific column where the entries are missing
heart_dis_subset.loc[:,"Age"] = heart_dis_subset["Age"].astype("int") # Update the datatype of the Age from Float ==> integer
heart_dis_subset.head(10)

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Exercise Type,Smoking,Family Heart Disease,Diabetes,BMI,...,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Updated Sleep Hours
0,56.0,Male,153.0,155.0,High,Walking,Yes,Yes,No,24.991591,...,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No,9.633228
1,69.0,Female,146.0,286.0,High,Walking,No,Yes,Yes,25.221799,...,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No,10.744034
2,46.0,Male,126.0,216.0,Low,Walking,No,No,No,29.855447,...,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No,6.440440
3,32.0,Female,122.0,293.0,High,Walking,Yes,Yes,No,24.130477,...,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No,7.249405
4,60.0,Male,166.0,242.0,Low,Walking,Yes,Yes,Yes,20.486289,...,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No,9.030971
5,25.0,Male,152.0,257.0,Low,Walking,Yes,No,No,28.144681,...,Low,Medium,5.504876,Low,126.0,91.0,4.297575,10.815983,No,7.504876
6,78.0,Female,121.0,175.0,High,Walking,Yes,Yes,Yes,18.042332,...,Medium,Medium,9.240911,Medium,107.0,85.0,11.582983,19.659461,No,11.240911
7,38.0,Female,161.0,187.0,Low,Walking,Yes,Yes,Yes,34.736683,...,Low,Medium,7.841008,High,228.0,111.0,4.929381,17.146599,No,9.841008
8,56.0,Female,135.0,291.0,Low,Walking,No,Yes,Yes,34.493112,...,High,Low,6.941403,High,317.0,103.0,5.119015,6.051129,No,8.941403
9,75.0,Male,144.0,252.0,Low,Walking,Yes,Yes,No,30.142149,...,Low,Medium,4.002662,High,199.0,96.0,10.005698,7.604357,No,6.002662

##### 1.2 filter out a subset of the data based on the following criteria and modify the data.
- female (sorted in age ascending order)
- get a subset

In [29]:
# filter out the female in the data and sort by age
# get the top 33 in the list and add the synthetic patient id to the data

is_female = heart_dis_subset["Gender"] == "Female"
eighteen_years_female = heart_dis_subset[is_female].sort_values(["Age"]).head(33)

##### 1.3 Add the synthetic patient id to the subset

In [30]:
# combine the synthetic data with the patient id to the created subset

# read in the CSV
# save only the patient id
# concatenate the patient id to the rest of the dataset

list_with_patient_id_1 = pd.read_csv("../notebooks/project-dataset/female_data.csv")
list_with_patient_id_1 = list_with_patient_id_1["Patient ID"]

list_with_patient_id_1 = pd.concat([list_with_patient_id_1.reset_index(drop=True), eighteen_years_female.reset_index(drop=True)], axis=1)

##### Step 2
Extract a subset of heart disease data and add the patient ids from the male_data

##### 2.1 filter out a subset of the data based on the following criteria and modify the data.
- male (sorted in age ascending order)
- get a subset

In [31]:
# filter out the male in the data and sort by age
# get the top 33 in the list and add the synthetic patient id to the data

is_male = heart_dis_subset["Gender"] == "Male"
eighteen_years_male = heart_dis_subset[is_male].sort_values(["Age"]).head(33)

##### 2.2 Add the synthetic patient id to the subset

In [32]:
# combine the synthetic data with the patient id to the created subset

# read in the CSV
# save only the patient id
# concatenate the patient id to the rest of the dataset

list_with_patient_id_2 = pd.read_csv("../notebooks/project-dataset/male_data.csv")
list_with_patient_id_2 = list_with_patient_id_2["Patient ID"]

list_with_patient_id_2 = pd.concat([list_with_patient_id_2.reset_index(drop=True), eighteen_years_male.reset_index(drop=True)], axis=1)

##### 2.3 Finally combine the two lists to make the new heart disease subset to illustrate joins

In [33]:
heart_disease_with_patient_id = pd.concat([list_with_patient_id_1, list_with_patient_id_2], ignore_index=True).sort_index()
heart_disease_with_patient_id

,Patient ID,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Exercise Type,Smoking,Family Heart Disease,Diabetes,...,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Updated Sleep Hours
0,PA001,18.0,Female,144.0,181.0,Medium,Walking,No,Yes,Yes,...,NaN,High,4.400117,Low,329.0,120.0,4.420417,16.359750,Yes,6.400117
1,PA002,18.0,Female,144.0,217.0,Low,Walking,Yes,Yes,No,...,NaN,Medium,9.053182,High,272.0,86.0,1.795393,17.276055,No,11.053182
2,PA003,18.0,Female,175.0,159.0,High,Walking,Yes,Yes,No,...,Low,Medium,4.298669,Medium,165.0,110.0,10.473899,19.483081,No,6.298669
3,PA004,18.0,Female,124.0,159.0,Medium,Walking,Yes,Yes,Yes,...,Low,Medium,4.214393,High,269.0,98.0,10.281038,5.958982,No,6.214393
4,PA005,18.0,Female,150.0,272.0,Medium,Walking,Yes,No,No,...,High,Low,6.178498,Low,327.0,83.0,10.024418,5.674116,No,8.178498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,TMG1616,18.0,Male,173.0,296.0,High,Walking,No,Yes,Yes,...,Medium,Low,6.886427,Medium,361.0,87.0,10.112107,10.570394,No,8.886427
62,WIJ7502,18.0,Male,160.0,159.0,High,Walking,Yes,No,Yes,...,NaN,Low,5.261115,High,235.0,116.0,9.758605,11.974975,No,7.261115
63,XBV1039,18.0,Male,177.0,231.0,Medium,Walking,No,Yes,Yes,...,Medium,Low,6.327760,Medium,358.0,131.0,1.247447,14.123586,No,8.327760
64,PPR0219,18.0,Male,157.0,231.0,Medium,Walking,Yes,Yes,No,...,Medium,NaN,9.561684,Medium,345.0,109.0,1.835666,17.721244,No,11.561684
65,APJ5125,18.0,Male,155.0,214.0,High,Walking,Yes,No,Yes,...,High,High,6.559073,Low,238.0,114.0,9.691328,14.562519,No,8.559073

### Comparison 6

#### Joins

This section illustrates different joins possible in python

For the purpose of these examples, the ***left table*** is the ***heart attack risk data*** and the ***right table*** is the ***heart disease data***

| Join Type     | Description
|-----------    |-----------------------------------------------------------------------------------------------------------------
| Inner Join    | Show patients that are in both datasets
| Left Join     | Show all the patients that are in the heart attack risk, and only those that match from the heart disease data
| Right Join    | Show all the patients from the heart disease data and only those that match from the heart attack risk.
| Outer Join    | Show all the patients from both heart disease data and heart attack risk data and match them where possible.

**Inner Join** <br>
Show patients that are in both datasets
- Display all the columns
- Display a subset of the columns - Age, Sex, Cholesterol level, Blood Pressure, Heart Rate, Family History

In [34]:
# Show patients that are in both datasets and display all the columns
patients_in_both_datasets = heart_att.merge(heart_disease_with_patient_id, how="inner", on="Patient ID", suffixes=[" - HeartAttackData", " - HeartDiseaseData"])
patients_in_both_datasets #36 rows

,Patient ID,Age - HeartAttackData,Sex,Cholesterol,Blood Pressure - HeartAttackData,Heart Rate,Diabetes - HeartAttackData,Family History,Smoking - HeartAttackData,Obesity,...,Alcohol Consumption - HeartDiseaseData,Stress Level - HeartDiseaseData,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Updated Sleep Hours
0,CSV3638,18,Female,353,159/108,46,0,0,0,1,...,Medium,High,9.415866,Low,351.0,80.0,4.385741,16.029884,No,11.415866
1,ZMF2605,18,Female,356,137/64,48,0,0,0,0,...,High,Medium,5.717311,High,174.0,127.0,11.101175,8.673891,No,7.717311
2,VUW1193,18,Male,163,142/67,51,1,0,1,0,...,Low,High,9.452650,Low,296.0,103.0,3.702488,13.921516,No,11.452650
3,PPR0219,18,Male,199,172/99,63,0,0,1,0,...,Medium,NaN,9.561684,Medium,345.0,109.0,1.835666,17.721244,No,11.561684
4,WIJ7502,18,Male,191,138/87,77,1,0,1,1,...,NaN,Low,5.261115,High,235.0,116.0,9.758605,11.974975,No,7.261115
5,MUH8083,18,Female,335,96/103,77,0,1,0,1,...,NaN,Medium,9.575884,Medium,379.0,101.0,11.480786,9.953602,No,11.575884
6,CCO3031,18,Female,236,93/67,107,0,1,0,1,...,Medium,Low,8.389512,Low,223.0,101.0,0.293733,5.890251,No,10.389512
7,APJ5125,18,Male,202,132/107,89,1,0,1,1,...,High,High,6.559073,Low,238.0,114.0,9.691328,14.562519,No,8.559073
8,XBV1039,18,Male,197,142/92,63,1,1,1,1,...,Medium,Low,6.327760,Medium,358.0,131.0,1.247447,14.123586,No,8.327760
9,SGL8650,18,Female,385,151/74,71,1,1,0,0,...,High,High,5.270622,Medium,288.0,129.0,1.627280,5.915055,No,7.270622
10,UEF3030,18,Female,229,160/63,72,0,1,0,1,...,Medium,Low,6.483957,Low,326.0,125.0,1.223178,10.092743,No,8.483957
11,JLN7780,18,Female,243,152/103,108,1,1,0,0,...,Low,High,5.570177,High,158.0,142.0,8.250325,5.164054,No,7.570177
12,XRE0129,18,Female,221,136/99,79,0,1,0,1,...,NaN,Medium,6.474971,High,201.0,137.0,0.837040,7.449411,No,8.474971
13,VXF5746,18,Female,379,114/101,94,1,1,0,1,...,Low,Medium,9.908529,High,236.0,129.0,4.309330,9.769662,No,11.908529
14,FNC9849,18,Male,166,105/77,91,1,0,1,1,...,NaN,High,4.899594,High,155.0,154.0,1.315860,15.775665,No,6.899594
15,DOK6965,18,Female,256,128/60,49,1,0,0,0,...,Medium,Medium,6.305006,Low,282.0,143.0,13.948725,9.416863,No,8.305006
16,EOY4699,18,Male,166,139/96,59,1,1,1,0,...,NaN,High,4.791021,Low,118.0,112.0,13.203185,18.716444,Yes,6.791021
17,YBF7973,18,Female,237,159/77,85,0,1,0,1,...,Low,High,8.343947,Medium,285.0,107.0,8.500739,6.999360,Yes,10.343947
18,KGL3058,18,Male,174,106/68,53,0,0,1,0,...,High,High,7.136219,Medium,105.0,114.0,1.821993,16.008513,No,9.136219
19,SFE5701,18,Female,352,164/93,110,1,1,0,1,...,High,Medium,6.979201,Low,276.0,83.0,10.922749,15.967185,Yes,8.979201
20,XZK0384,18,Female,264,99/105,78,1,1,0,1,...,High,High,6.623844,Medium,181.0,147.0,5.594147,14.335284,No,8.623844
21,OYX4627,18,Female,276,110/63,52,1,1,0,1,...,NaN,Medium,4.722851,Medium,280.0,138.0,3.732792,8.612439,Yes,6.722851
22,QHF4485,18,Male,168,141/90,53,0,0,1,0,...,NaN,Medium,6.570419,High,378.0,90.0,6.263468,6.395926,No,8.570419
23,GWZ2697,18,Male,172,168/71,83,0,0,1,1,...,Medium,Low,4.588648,Low,112.0,98.0,1.848430,13.649218,No,6.588648
24,VRS2034,18,Female,233,136/93,74,0,1,0,0,...,Low,High,5.101511,Medium,188.0,116.0,13.848278,12.769829,No,7.101511
25,WZR8579,18,Female,396,126/77,89,0,1,0,0,...,NaN,Medium,5.096933,Medium,336.0,154.0,9.944048,17.777623,No,7.096933
26,YTR5694,18,Female,220,120/95,81,0,1,0,1,...,Low,Low,6.779747,High,367.0,150.0,9.793477,14.355436,No,8.779747
27,SQC5793,18,Male,159,117/91,83,1,1,1,0,...,Medium,Medium,7.322308,Medium,297.0,115.0,7.718714,16.982790,Yes,9.322308
28,ROM7758,18,Male,167,116/78,107,1,1,1,1,...,Low,Low,9.148867,High,138.0,129.0,13.764714,7.757238,No,11.148867
29,JRW1358,18,Female,382,104/85,70,1,0,0,1,...,High,Low,5.379767,High,298.0,127.0,2.699510,13.929931,Yes,7.379767
30,IJM9697,18,Male,170,145/70,78,0,1,1,0,...,Low,Medium,4.162370,Low,118.0,91.0,13.242543,8.313291,No,6.162370
31,SJH8575,18,Male,171,128/76,80,1,0,1,0,...,Medium,High,NaN,Medium,124.0,149.0,4.860209,16.516323,No,NaN
32,TZZ3208,18,Male,172,90/78,82,0,1,1,0,...,High,High,9.955651,High,267.0,82.0,0.596968,12.357894,No,11.955651
33,PGS8412,18,Male,167,158/81,87,1,0,1,0,...,NaN,Low,6.316221,High,151.0,158.0,10.049290,9.469909,No,8.316221
34,ZLU5930,18,Male,177,109/72,105,1,1,1,0,...,Low,High,7.096736,Medium,172.0,98.0,3.806334,11.418889,No,9.096736
35,TMG1616,18,Male,186,111/66,58,0,0,1,1,...,Medium,Low,6.886427,Medium,361.0,87.0,10.112107,10.570394,No,8.886427

In [35]:
# Show patients that are in both datasets and display a subset of the columns:  Age, Gender, Cholesterol level, Blood Pressure, Family History
patients_in_both_datasets[["Patient ID", "Age - HeartAttackData", "Gender", "Cholesterol", "Cholesterol Level", "Blood Pressure - HeartAttackData", "Blood Pressure - HeartDiseaseData", "Family History", "Family Heart Disease"]]

,Patient ID,Age - HeartAttackData,Gender,Cholesterol,Cholesterol Level,Blood Pressure - HeartAttackData,Blood Pressure - HeartDiseaseData,Family History,Family Heart Disease
0,CSV3638,18,Female,353,264.0,159/108,132.0,0,Yes
1,ZMF2605,18,Female,356,281.0,137/64,150.0,0,Yes
2,VUW1193,18,Male,163,243.0,142/67,175.0,0,No
3,PPR0219,18,Male,199,231.0,172/99,157.0,0,Yes
4,WIJ7502,18,Male,191,159.0,138/87,160.0,0,No
5,MUH8083,18,Female,335,253.0,96/103,153.0,1,No
6,CCO3031,18,Female,236,276.0,93/67,140.0,1,Yes
7,APJ5125,18,Male,202,214.0,132/107,155.0,0,No
8,XBV1039,18,Male,197,231.0,142/92,177.0,1,Yes
9,SGL8650,18,Female,385,206.0,151/74,171.0,1,Yes
10,UEF3030,18,Female,229,170.0,160/63,174.0,1,Yes
11,JLN7780,18,Female,243,299.0,152/103,141.0,1,No
12,XRE0129,18,Female,221,272.0,136/99,134.0,1,Yes
13,VXF5746,18,Female,379,158.0,114/101,173.0,1,No
14,FNC9849,18,Male,166,155.0,105/77,168.0,0,Yes
15,DOK6965,18,Female,256,265.0,128/60,163.0,0,Yes
16,EOY4699,18,Male,166,262.0,139/96,155.0,1,Yes
17,YBF7973,18,Female,237,248.0,159/77,144.0,1,Yes
18,KGL3058,18,Male,174,169.0,106/68,121.0,0,Yes
19,SFE5701,18,Female,352,166.0,164/93,174.0,1,Yes
20,XZK0384,18,Female,264,183.0,99/105,147.0,1,Yes
21,OYX4627,18,Female,276,152.0,110/63,126.0,1,No
22,QHF4485,18,Male,168,272.0,141/90,147.0,0,No
23,GWZ2697,18,Male,172,151.0,168/71,177.0,0,Yes
24,VRS2034,18,Female,233,277.0,136/93,178.0,1,No
25,WZR8579,18,Female,396,247.0,126/77,148.0,1,No
26,YTR5694,18,Female,220,258.0,120/95,143.0,1,Yes
27,SQC5793,18,Male,159,290.0,117/91,180.0,1,Yes
28,ROM7758,18,Male,167,210.0,116/78,180.0,1,Yes
29,JRW1358,18,Female,382,276.0,104/85,158.0,0,No
30,IJM9697,18,Male,170,254.0,145/70,148.0,1,No
31,SJH8575,18,Male,171,212.0,128/76,167.0,0,No
32,TZZ3208,18,Male,172,242.0,90/78,129.0,1,No
33,PGS8412,18,Male,167,271.0,158/81,143.0,0,Yes
34,ZLU5930,18,Male,177,270.0,109/72,180.0,1,No
35,TMG1616,18,Male,186,296.0,111/66,173.0,0,Yes

**Left Join**<br>

Show all the patients that are in the heart attack risk (left table), and only those that match from the heart disease data (right table)
- Display all the columns
- Display a subset of the columns - Age, Sex, Cholesterol level, Blood Pressure, Heart Rate, Family History

In [36]:
# Show all the patients that are in the heart attack risk (left table), and only those that match from the heart disease data (right table) and display all the columns
left_join_on_datasets = heart_att.merge(heart_disease_with_patient_id, how="left", on="Patient ID", suffixes=[" - HeartAttackData", " - HeartDiseaseData"])
left_join_on_datasets #8,763 rows

,Patient ID,Age - HeartAttackData,Sex,Cholesterol,Blood Pressure - HeartAttackData,Heart Rate,Diabetes - HeartAttackData,Family History,Smoking - HeartAttackData,Obesity,...,Alcohol Consumption - HeartDiseaseData,Stress Level - HeartDiseaseData,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Updated Sleep Hours
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CZE1114,21,Male,389,165/93,98,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BNI9906,21,Female,324,174/99,72,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,JLN3497,84,Male,383,163/100,73,1,1,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GFO8847,66,Male,318,91/88,93,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,MSV9918,60,Male,121,94/76,61,1,1,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8759,QSV6764,28,Female,120,157/102,73,1,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8760,XKA5925,47,Male,250,161/75,105,0,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8761,EPE6801,36,Male,178,119/67,60,1,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8762,ZWN9666,25,Female,356,138/67,75,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
# Show all the patients that are in the heart attack risk (left table), and only those that match from the heart disease data (right table) and display a subset of the columns:  
# Age, Gender, Cholesterol level, Blood Pressure, Family History
left_join_on_datasets[["Patient ID", "Age - HeartAttackData", "Gender", "Cholesterol", "Cholesterol Level", "Blood Pressure - HeartAttackData", "Blood Pressure - HeartDiseaseData", "Family History", "Family Heart Disease"]]

,Patient ID,Age - HeartAttackData,Gender,Cholesterol,Cholesterol Level,Blood Pressure - HeartAttackData,Blood Pressure - HeartDiseaseData,Family History,Family Heart Disease
0,BMW7812,67,NaN,208,NaN,158/88,NaN,0,NaN
1,CZE1114,21,NaN,389,NaN,165/93,NaN,1,NaN
2,BNI9906,21,NaN,324,NaN,174/99,NaN,0,NaN
3,JLN3497,84,NaN,383,NaN,163/100,NaN,1,NaN
4,GFO8847,66,NaN,318,NaN,91/88,NaN,1,NaN
...,...,...,...,...,...,...,...,...,...
8758,MSV9918,60,NaN,121,NaN,94/76,NaN,1,NaN
8759,QSV6764,28,NaN,120,NaN,157/102,NaN,0,NaN
8760,XKA5925,47,NaN,250,NaN,161/75,NaN,1,NaN
8761,EPE6801,36,NaN,178,NaN,119/67,NaN,0,NaN
8762,ZWN9666,25,NaN,356,NaN,138/67,NaN,1,NaN

**Right Join**<br>
Show all the patients from the heart disease data (right table) and only those that match from the heart attack risk data (left table).
- Display all the columns
- Display a subset of the columns - Age, Sex, Cholesterol level, Blood Pressure, Heart Rate, Family History

In [39]:
# Show all the patients from the heart disease data (right table) and only those that match from the heart attack risk data (left table) and display all the columns
right_join_on_datasets = heart_att.merge(heart_disease_with_patient_id, how="right", on="Patient ID", suffixes=[" - HeartAttackData", " - HeartDiseaseData"])
right_join_on_datasets #66 rows

,Patient ID,Age - HeartAttackData,Sex,Cholesterol,Blood Pressure - HeartAttackData,Heart Rate,Diabetes - HeartAttackData,Family History,Smoking - HeartAttackData,Obesity,...,Alcohol Consumption - HeartDiseaseData,Stress Level - HeartDiseaseData,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Updated Sleep Hours
0,PA001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,High,4.400117,Low,329.0,120.0,4.420417,16.359750,Yes,6.400117
1,PA002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Medium,9.053182,High,272.0,86.0,1.795393,17.276055,No,11.053182
2,PA003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Low,Medium,4.298669,Medium,165.0,110.0,10.473899,19.483081,No,6.298669
3,PA004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Low,Medium,4.214393,High,269.0,98.0,10.281038,5.958982,No,6.214393
4,PA005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,High,Low,6.178498,Low,327.0,83.0,10.024418,5.674116,No,8.178498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,TMG1616,18.0,Male,186.0,111/66,58.0,0,0,1,1,...,Medium,Low,6.886427,Medium,361.0,87.0,10.112107,10.570394,No,8.886427
62,WIJ7502,18.0,Male,191.0,138/87,77.0,1,0,1,1,...,NaN,Low,5.261115,High,235.0,116.0,9.758605,11.974975,No,7.261115
63,XBV1039,18.0,Male,197.0,142/92,63.0,1,1,1,1,...,Medium,Low,6.327760,Medium,358.0,131.0,1.247447,14.123586,No,8.327760
64,PPR0219,18.0,Male,199.0,172/99,63.0,0,0,1,0,...,Medium,NaN,9.561684,Medium,345.0,109.0,1.835666,17.721244,No,11.561684
65,APJ5125,18.0,Male,202.0,132/107,89.0,1,0,1,1,...,High,High,6.559073,Low,238.0,114.0,9.691328,14.562519,No,8.559073

In [40]:
# Show all the patients from the heart disease data (right table) and only those that match from the heart attack risk data (left table) and display a subset of the columns  
# Age, Gender, Cholesterol level, Blood Pressure, Family History
right_join_on_datasets[["Patient ID", "Age - HeartAttackData", "Gender", "Cholesterol", "Cholesterol Level", "Blood Pressure - HeartAttackData", "Blood Pressure - HeartDiseaseData", "Family History", "Family Heart Disease"]]

,Patient ID,Age - HeartAttackData,Gender,Cholesterol,Cholesterol Level,Blood Pressure - HeartAttackData,Blood Pressure - HeartDiseaseData,Family History,Family Heart Disease
0,PA001,NaN,Female,NaN,181.0,NaN,144.0,NaN,Yes
1,PA002,NaN,Female,NaN,217.0,NaN,144.0,NaN,Yes
2,PA003,NaN,Female,NaN,159.0,NaN,175.0,NaN,Yes
3,PA004,NaN,Female,NaN,159.0,NaN,124.0,NaN,Yes
4,PA005,NaN,Female,NaN,272.0,NaN,150.0,NaN,No
...,...,...,...,...,...,...,...,...,...
61,TMG1616,18.0,Male,186.0,296.0,111/66,173.0,0,Yes
62,WIJ7502,18.0,Male,191.0,159.0,138/87,160.0,0,No
63,XBV1039,18.0,Male,197.0,231.0,142/92,177.0,1,Yes
64,PPR0219,18.0,Male,199.0,231.0,172/99,157.0,0,Yes
65,APJ5125,18.0,Male,202.0,214.0,132/107,155.0,0,No

**Outer Join**<br>
Show all the patients from both heart attack risk and heart disease data and match them where possible
- Display all the columns
- Display a subset of the columns - Age, Sex, Cholesterol level, Blood Pressure, Heart Rate, Family History

In [41]:
# Show all the patients from both heart attack risk and heart disease data and match them where possible and display all the columns
outer_join_on_datasets = heart_att.merge(heart_disease_with_patient_id, how="outer", on="Patient ID", suffixes=[" - HeartAttackData", " - HeartDiseaseData"])
outer_join_on_datasets #8,793 rows

,Patient ID,Age - HeartAttackData,Sex,Cholesterol,Blood Pressure - HeartAttackData,Heart Rate,Diabetes - HeartAttackData,Family History,Smoking - HeartAttackData,Obesity,...,Alcohol Consumption - HeartDiseaseData,Stress Level - HeartDiseaseData,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Updated Sleep Hours
0,AAA9246,61.0,Male,171.0,148/90,89.0,1,1,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AAC3641,57.0,Female,232.0,144/93,73.0,0,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AAD0466,20.0,Female,357.0,159/91,75.0,1,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AAD3011,21.0,Male,165.0,106/103,76.0,1,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AAE4089,52.0,Female,335.0,165/63,43.0,0,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8788,ZZI5174,19.0,Male,143.0,167/93,57.0,0,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8789,ZZQ4895,49.0,Male,279.0,177/70,86.0,1,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8790,ZZT7113,49.0,Female,297.0,158/88,69.0,0,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8791,ZZU2948,25.0,Female,238.0,136/76,81.0,0,1,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8792,ZZY4724,35.0,Male,352.0,157/67,81.0,0,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
# Show all the patients from both heart attack risk and heart disease data and match them where possible and display a subset of the columns:  
# Age, Gender, Cholesterol level, Blood Pressure, Family History
outer_join_on_datasets[["Patient ID", "Age - HeartAttackData", "Gender", "Cholesterol", "Cholesterol Level", "Blood Pressure - HeartAttackData", "Blood Pressure - HeartDiseaseData", "Family History", "Family Heart Disease"]]

,Patient ID,Age - HeartAttackData,Gender,Cholesterol,Cholesterol Level,Blood Pressure - HeartAttackData,Blood Pressure - HeartDiseaseData,Family History,Family Heart Disease
0,AAA9246,61.0,NaN,171.0,NaN,148/90,NaN,1,NaN
1,AAC3641,57.0,NaN,232.0,NaN,144/93,NaN,1,NaN
2,AAD0466,20.0,NaN,357.0,NaN,159/91,NaN,0,NaN
3,AAD3011,21.0,NaN,165.0,NaN,106/103,NaN,0,NaN
4,AAE4089,52.0,NaN,335.0,NaN,165/63,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...
8788,ZZI5174,19.0,NaN,143.0,NaN,167/93,NaN,0,NaN
8789,ZZQ4895,49.0,NaN,279.0,NaN,177/70,NaN,0,NaN
8790,ZZT7113,49.0,NaN,297.0,NaN,158/88,NaN,0,NaN
8791,ZZU2948,25.0,NaN,238.0,NaN,136/76,NaN,1,NaN
8792,ZZY4724,35.0,NaN,352.0,NaN,157/67,NaN,0,NaN

#### Summary <br>
 
> This notebook showcases various pandas operations that closely mirror common SQL commands. Leveraging my SQL background, I have been able to apply and demonstrate equivalent techniques in pandas, highlighting how familiar SQL concepts translate seamlessly into Python-based data analysis.